title: "Brenes Census Portfolio"
description: "Software Developer & Cybersecurity Enthusiast"
markdown: kramdown

theme: null
baseurl: ""
url: "https://brenescensus.github.io"

include:
  - assets
  - labs

defaults:
  - scope:
      path: "labs"
    values:
      layout: null

collections:
   labs:
    output: true
    permalink: /labs/:path/