title: "Brenes Census Portfolio"
description: "Software Developer & Cybersecurity Enthusiast"
markdown: kramdown
theme: null
baseurl: ""
url: "https://brenescensus.github.io"

# Allow custom folders
include:
  - assets
  - labs

# Jekyll page defaults
defaults:
  - scope:
      path: "labss"
      type: "pages"
    values:
      layout: lab
